# Generated by Django 3.2.13 on 2023-10-02 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filmes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=70)),
                ('diretor', models.CharField(max_length=70)),
                ('genero', models.CharField(max_length=20)),
                ('anoLancamento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Opinioes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headlineDaOpiniao', models.CharField(max_length=100)),
                ('tituloFilme', models.CharField(max_length=70)),
                ('diretorFilme', models.CharField(max_length=70)),
                ('anoLancamentoFilme', models.DateField()),
            ],
        ),
    ]
